# Generated by Django 5.0.7 on 2024-08-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.FileField(blank=True, default='cta.jpg', null=True, upload_to='stting'),
        ),
    ]
