# Generated by Django 5.0.7 on 2024-07-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='image',
            field=models.FileField(blank=True, default='herosection.jpg', null=True, upload_to='herosection'),
        ),
    ]
