# Generated by Django 5.0.7 on 2024-08-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_herosection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='title_one',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_two',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
