# Generated by Django 5.0.7 on 2024-08-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_companystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('url_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiderFeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, default='featuer.jpg', null=True, upload_to='herosection')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feature_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sider_features', to='home.featuresection')),
            ],
        ),
    ]
