# Generated by Django 5.0.7 on 2024-08-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_featuresection_siderfeaturesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.FileField(blank=True, default='featuer.jpg', null=True, upload_to='herosection')),
                ('iphone_url', models.URLField(blank=True, null=True)),
                ('android_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
