# Generated by Django 5.0.7 on 2024-08-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_appsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsection',
            old_name='icon',
            new_name='image',
        ),
    ]
