# Generated by Django 5.0.7 on 2024-08-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_icon_appsection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('url_name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, default='Carddeal.jpg', null=True, upload_to='herosection')),
            ],
        ),
    ]
